spring:
  application:
    name: fiap-fastfood-customer

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:postgresql://${CUSTOMER_DB_URL:localhost}:${CUSTOMER_DB_PORT:5432}/fastfood-customer
    username: ${CUSTOMER_DB_USER:fastfood}
    password: ${CUSTOMER_DB_PASSWORD:Postgres2024!}

management:
  endpoint:
    loggers:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
