spring:
  application:
    name: fiap-fastfood-customer

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  data:
    r2dbc:
      repositories:
        enabled: true
  r2dbc:
    url: r2dbc:postgresql://${CUSTOMER_DB_URL:localhost}:${CUSTOMER_DB_PORT:5432}/fastfood-customer
    username: ${CUSTOMER_DB_USER:fastfood}
    password: ${CUSTOMER_DB_PASSWORD:Postgres2024!}

aws:
  sqs:
    customer:
      queue: ${CUSTOMER_QUEUE_NAME:customer_queue}
    numberOfMessages: 5
    waitTimeMessage: 10
    numberOfRetries: 10
    visibilityTimeOut: 30

management:
  endpoint:
    loggers:
      enabled: true
    health:
      probes:
        enabled: true
      show-details: "ALWAYS"
  endpoints:
    web:
      exposure:
        include: "*"
